import type { LucideProps } from "lucide-react";
import {
  ArrowRight,
  ArrowUp,
  BookOpen,
  Bot,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Bus,
  Camera,
  CheckCircle2,
  ChevronDown,
  CircleDot,
  Clapperboard,
  Cloud,
  CloudCog,
  Database,
  Factory,
  FileText,
  FlaskConical,
  Globe,
  Globe2,
  GraduationCap,
  HeartPulse,
  Hospital,
  Hotel,
  Landmark,
  Layers,
  Leaf,
  LifeBuoy,
  Link2,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MonitorSmartphone,
  Moon,
  Package,
  PenTool,
  Phone,
  Radio,
  Rocket,
  Scale,
  School,
  Search,
  Server,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  UtensilsCrossed,
  X,
} from "lucide-react";

// Explicit named imports, not `import * as Icons`. A wildcard import lets
// callers index by any string, which defeats tree-shaking — every one of
// lucide-react's ~1600 icons would end up in the bundle even though only
// this set is ever used. Add new icons here (and to the map below) as
// content grows; this keeps the bundle scoped to what's actually used.
const registry = {
  ArrowRight,
  ArrowUp,
  BookOpen,
  Bot,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Bus,
  Camera,
  CheckCircle2,
  ChevronDown,
  CircleDot,
  Clapperboard,
  Cloud,
  CloudCog,
  Database,
  Factory,
  FileText,
  FlaskConical,
  Globe,
  Globe2,
  GraduationCap,
  HeartPulse,
  Hospital,
  Hotel,
  Landmark,
  Layers,
  Leaf,
  LifeBuoy,
  Link2,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MonitorSmartphone,
  Moon,
  Package,
  PenTool,
  Phone,
  Radio,
  Rocket,
  Scale,
  School,
  Search,
  Server,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  UtensilsCrossed,
  X,
} satisfies Record<string, React.ComponentType<LucideProps>>;

export type IconName = keyof typeof registry;

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = registry[name as IconName];
  if (!Cmp) return <CircleDot {...props} />;
  return <Cmp {...props} />;
}
